# Generated by Django 4.0.6 on 2022-10-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(blank=True, max_length=200, null=True)),
                ('forma_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('tipo_de_cobro', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('nombre_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('titular_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('monto_de_pago', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
