# Generated by Django 4.0.6 on 2022-10-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='miembroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro_fields', models.CharField(max_length=200)),
            ],
        ),
    ]
