# Generated by Django 4.0.6 on 2022-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='area',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
