# Generated by Django 4.0.6 on 2022-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_empresa', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_de_ruc', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_del_nexo', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono_del_nexo', models.CharField(blank=True, max_length=250, null=True)),
                ('mail_del_nexo', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_contacto_pagos', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono_contacto_pagos', models.CharField(blank=True, max_length=250, null=True)),
                ('mail_contacto_pagos', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_de_vinculacion', models.CharField(blank=True, max_length=50, null=True)),
                ('notas_adicionales', models.CharField(blank=True, max_length=250, null=True)),
                ('forma_de_pago_habitual', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Cheque'), ('3', 'Transferencia'), ('4', 'Deposito')], max_length=20)),
                ('banco', models.CharField(blank=True, max_length=250, null=True)),
                ('titular_de_la_cuenta', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_de_cuenta', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_de_cuenta', models.CharField(blank=True, max_length=250, null=True)),
                ('documento_de_cuenta', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
