# Generated by Django 4.0.6 on 2022-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='hora_entrega',
            field=models.TimeField(default=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
