# Generated by Django 4.0.6 on 2022-10-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=250)),
                ('contraseña', models.CharField(max_length=250)),
                ('rol', models.CharField(blank=True, max_length=250, null=True)),
                ('vinculacion', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_usuario', models.CharField(choices=[('1', 'Master'), ('2', 'Editor'), ('3', 'Financiero'), ('4', 'Visualizador')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
