# Generated by Django 4.0.6 on 2022-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'Colaborador'), ('2', 'Proveedor')], max_length=50),
        ),
    ]
